version: '3'
services:
  corese:
    image: frmichel/corese-sd
    build: ./corese-sd
    networks:
      - sms-net
    ports:
      - "8081:8081"
    volumes:
      - "./logs:/usr/local/corese/log"
  mongo:
    image: mongo:3.6-jessie
    networks:
      - sms-net
  sparql-micro-service:
    image: frmichel/sparql-micro-service
    build: ./sparql-micro-service
    networks:
      - sms-net
    ports:
      - "80:80"
    volumes:
      - "./logs:/var/www/html/sparql-ms/logs"
networks:
  sms-net:
    driver: bridge


